<script type='text/javascript'>

</script>
<div id="global_header">
	<div id="header-left">
		<a href="/myhome"><img src="/images/placeweb.png" alt="Place Web logo" /></a>
		<div id="project-name">Physics Learning Across Contexts &amp; Environments</div>
	</div>
<?php
if(isset($_SESSION['access'])) {
?>
	<div id="header-right">
		
		
		<div class='buttonset'>
			<button class='' href="/myhome/preferences">
				<?php echo $_SESSION['user_display_name']?>
				<img title="User Profile" src="/images/user-icon.png" style='height: 20px;'/>
			</button>
			
			<button class='' onClick="loadWeb()">
				Knowledge Web
				<img title="Launch Associative Web" src="/images/knol-web.png" style='height: 20px;'/>
			</button>
			
			<button class='' href="/user/logout">
				logout
				<img title="Manage Class" height="20px" src="/images/button-power.png"/>
			</button>
		</div>
		
	</div>
<?php 
}
?>

	<div class="clear"></div>
</div><!-- /global_header -->

