<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
	<head>
		<meta charset="utf-8">
		
		<title>
			PLACE.web
		</title>
		
		<!-- 						EXTERNAL CSS		 					-->		
		<link type="text/css" rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/cupertino/jquery-ui.css">
		<link type="text/css" rel="stylesheet" href="/jquery/jqueryfileupload/jquery.fileupload-ui.css">
		<link type="text/css" rel="stylesheet" href="/css/dataTables.css">
		<link type="text/css" rel="stylesheet" href="/css/dataTables.page.css">
		<link type="text/css" rel="stylesheet" href="/css/dataTables.jui.css">
		<link type="text/css" rel="stylesheet" href="/css/absolution.blue.css">
		<link type="text/css" rel="stylesheet" href="/css/styles.css">
		
		<!-- 						EXTERNAL JAVASCRIPT 					-->
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"></script>
		<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js"></script>
		<script type="text/javascript" src="/jquery/jqueryfileupload/jquery.iframe-transport.js"></script>
		<script type="text/javascript" src="/jquery/jqueryfileupload/jquery.fileupload.js"></script>
		<script type="text/javascript" src="/jquery/jqueryfileupload/jquery.fileupload-ui.js"></script>
		<script type="text/javascript" src="/jquery/jplayer/jquery.jplayer.min.js"></script>
		<script type="text/javascript" src="/jquery/dataTables/jquery.dataTables.min.js"></script>
		<script type="text/javascript" src="/jquery/jquery-uniform.js"></script>
		<script type="text/javascript" src="/js/basic.js"></script>
		<script type="text/javascript" src="/js/less.js"></script>
		<script type="text/javascript" src="/swampy_browser/sb.js"></script>
		<script type="text/javascript" src="/tinymce/jscripts/tiny_mce/tiny_mce.js"></script>
		<script type="text/javascript" src="/tinymce/jscripts/tiny_mce/tinymce.head.js"></script>
		
		<script type='text/javascript'>
		$(document).ready(function () {
			$("button").button()
			
			$("button[href]").click(function(){
				window.location.href = $(this).attr('href')
			})
			
			$(".buttonset").buttonset()
			
			$("input:file, input:checkbox, input:radio, select").uniform()
		})
		</script>
	</head>
	
	
	<body>
		<div id="web-container-mask" class="div-hide"></div>
		
		
		<div id="container">
			<?= $this->partial('header.partial.phtml')?>
			
			<div id="main_content">
				<?php echo $this->layout()->content ?>
			</div>
			
			<?= $this->partial('footer.partial.phtml')?>
		</div>
		
		
		<div id="debugMode"></div>
	</body>
</html>